### ISSUE TITLE
suggestion for CSS classes

### ISSUE THREAD

**Issue by hyphone** [CalebJohn/joplin-rich-markdown#1]
Hi there,

thank you very much for those additions - I personally find them very useful!

Would it be possible to create a seperate class for list element markers?

So that we could style the markers of the list elements differently like so:
![grafik](https://user-images.githubusercontent.com/6410852/109437535-880f1300-7a25-11eb-84a5-3b5e5ba35ee4.png)

I find it quite distracting that the whole list item is coloured. This focuses my attention too much on the whole list element items instead of just noticing that it is a list element.

I'm looking forward to your response :)

**Comment by CalebJohn** [comment]
Hi @hyphone,

Thanks for the suggestion, I'm glad that you're liking the plugin. 

You'll be glad to know that I actually added [this class yesterday as part of another feature I'm working on](https://github.com/CalebJohn/joplin-rich-markdown/commit/bb54f4df3d0535229e3ebce8acf966101205aa7a). I'll add an example on how to get you're proposed look right away.

The class will be available in the next release, but if you want it immediately, [the jpl file is available here](https://github.com/CalebJohn/joplin-rich-markdown/tree/main/publish).
