### ISSUE TITLE
Heading Style is not as shown in the screenshots.

### ISSUE THREAD

**Issue by uroybd** [CalebJohn/joplin-rich-markdown#15]
Hi,

In the screenshot provided from this plugin, there aren't any preceding hashes in the header itself like this:

![as shown in screenshot](https://raw.githubusercontent.com/CalebJohn/joplin-rich-markdown/main/examples/welcome.png)

However, in my editor I see it like this:

![Screenshot from 2021-08-27 16-00-02](https://user-images.githubusercontent.com/4207230/131110524-2967d3d0-269b-4245-b557-83ccdd7f0537.png)

I don't have any additional CSS added or any custom theme enabled.

Might I be missing something?

**Comment by CalebJohn** [comment]
The heading style is an example of what can be done with this plugin. By default there aren't many style changes, but there are a number of css classes made available to the users that allow for such customization. In the future I plan to implement some default themes (including the one above).

The css in the demo image was provided by uxamand [on the forum](https://discourse.joplinapp.org/t/plugin-rich-markdown/15053/108?u=calebjohn). You can copy and paste that css into your userchrome.css file to get similar headings.
