### ISSUE TITLE
Bug: non http(s) links still open in a browser

### ISSUE THREAD

**Issue by msbentley** [CalebJohn/joplin-rich-markdown#17]
I'm really enjoying rich markdown, but today caught a small issue. I am using cb_thunderlink on linux which registers a new handler for thunderlink:// links with my OS (linux). I want to include such links in Joplin to be able to jump to specific emails from my notes.

These links work fine in the markdown preview and the OS correctly passes the link to Thunderbird, but in the editor with rich markdown enables these links attempt to open in a browser, e.g.

https://user-images.githubusercontent.com/1671065/131710649-89d2eb71-7077-43cd-b692-7cf5d10ca931.mp4

## Versions
- Joplin: 2.4.4
- Rich Markdown: 0.7.1
- OS: linux
- OS version: ubuntu 20.04

**Comment by CalebJohn** [comment]
Hi @msbentley, I've glad to hear that you're making use of the plugin. Sorry for getting to this so late. This is indeed a bug with the plugin, I'll try to have it fixed tonight.

**Comment by msbentley** [comment]
Great, the latest release works perfectly - many thanks!
