### ISSUE TITLE
Image changes not shown

### ISSUE THREAD

**Issue by okoetter** [CalebJohn/joplin-rich-markdown#18]
I opened the markdown preview, right clicked on an image and selected "Open...".
I then changed the size with an external tool and saved it. Markdown preview immediately showed the shrinked image while the rich markdown plugin did not.
Am I doing something wrong?

Joplin 2.3.5, 
Rich Markdown plugin V0.7.1

**Comment by CalebJohn** [comment]
Hi @okoetter, this is indeed a bug, or at least an oversight. I'll get this fixed up as soon as possible. Thanks for being patient.
