### ISSUE TITLE
Feature Request: handle img HTML elements

### ISSUE THREAD

**Issue by jrlacharnay** [CalebJohn/joplin-rich-markdown#2]
When an image is resized in the wysiwyg editor, it is converted to an "img" HTML element:

`<img src=":/259e369acff6476d9e8038398fa11d34" alt="5905fc3887df0e3ef1d1672bc03644c5.png" width="306" height="1323">`

Or:

`<img src=":/259e369acff6476d9e8038398fa11d34" alt="5905fc3887df0e3ef1d1672bc03644c5.png" width="74" height="320" class="jop-noMdConv">`

Instead of:

`![5905fc3887df0e3ef1d1672bc03644c5.png](:/259e369acff6476d9e8038398fa11d34)`

In that case, the image does not appear in the editor view.

It would be nice if this syntax could be supported as well (even without taking into account the width and height).

Thanks,
Jean-Rémy

**Comment by CalebJohn** [comment]
Thanks for the feature request. This makes a lot of sense, and I plan to include it in v0.4.0.

**Comment by CalebJohn** [comment]
I've added this in the latest commit, I plan to do a bit more testing before releasing v0.4.0 but should release by tomorrow or the day after. For now I'll close this so I don't forget to close it later.

It will take width into account but not height (which aligns with how the Joplin renderer handles images).

**Comment by jrlacharnay** [comment]
Thanks!!
