### ISSUE TITLE
Image change scanning jumps the cursor position

### ISSUE THREAD

**Issue by msbentley** [CalebJohn/joplin-rich-markdown#21]
In the latest version of the plugin (I'm on 0.7.2) the new option for image change scanning (default period 3s) keeps jumping the cursor position, but only in certain notes. I haven't yet found what is unique about these notes, but if I set the period for change scanning to 0, the problem goes away. It is not always the start, but it always jumps up...

I'll post more if I find the common denominator for the notes causing this issue!

OS: linux
Joplin ver: 2.4.7
Plugin ver: 0.7.2

**Comment by msbentley** [comment]
Note that another side-effect of this is that the spell-checker seems to re-refresh at this period - i.e. the red underlining of incorrect words vanishes and re-appears with the period set fore the image scanning.

**Comment by CalebJohn** [comment]
Thanks for reporting this @msbentley. In hindsight that scanning change was a bit half backed...

I've pushed up a fix now, please give it a test when you get the chance and let me know if it actually fixed your issue (it should have!).

**Comment by msbentley** [comment]
Thanks @CalebJohn I just tested the latest and the jumping around seems to have stopped - many thanks! The spell-checker refresh seems still to happen at the polled interval, so for now I've set that to a large number (since zero seems to stop it working).

**Comment by CalebJohn** [comment]
Setting it to zero does disable the periodic checking, but it will still check for changes after any change in the document. You might find that is enough.

That's strange, I can't duplicate it anymore even in my stress testing notes. I'll keep my eyes open for it and we'll see if it happens for anyone else.

**Comment by msbentley** [comment]
Thanks - I updated my second machine this morning and everything seems OK here, so perhaps it was something odd with my other install. So all good now, many thanks!
