### ISSUE TITLE
[Feature Request] Copy html/markdown formatted text to clipboard from WYSIWYG editor

### ISSUE THREAD

**Issue by NathanAuckett** [CalebJohn/joplin-rich-markdown#29]
Currently the behavior of copying text from the markdown preview and the WYSIWYG editor behave differently.

See this image bellow of a word document I've pasted into. Notice how the left does not retain the break lines wheres the right side does?
In this instance I actually want the result of the left side.
![image](https://user-images.githubusercontent.com/16657331/147199083-81cb7183-f044-49c0-b8f6-bca60b905864.png)

I don't know the exact cause of this but I presume markdown copies as html and WYSIWYG does not.
I'd like the ability to copy the HTML formatting of the markdown preview from the WYSIWYG editor, if possible.

The reason for this is the place where I copy my notes does not play nice with the WYSIWYG formatting whereas its fine with the markdown preview formatting.

This is a non-urgent quality of life feature request.
As is I cannot escape into the WYSIWYG editor without it :'(

Thanks in advance for any consideration into this request.

**Comment by CalebJohn** [comment]
Hi @NathanAuckett,

Thanks for the detailed request. I can see where you're coming from and agree that it would be nice to have a plugin that helps to control the content of what gets copied. There is a similar plugin that's been started to handling the pasting side, but copying is arguably equally important.

That said, it really is outside the scope of this plugin, which is about formatting within the markdown editor. In fact, one of the primary goals of this plugin is to get rid of the need for the markdown viewer and the WYSIWYG editor.

I'd encourage you to post this request on [the forum](https://discourse.joplinapp.org/) I can't guarantee that someone will pick it up, but you might get some useful discussion going with some tips to help you out.

Cheers!
