### ISSUE TITLE
Missing formatting for list items and marking

### ISSUE THREAD

**Issue by zblesk** [CalebJohn/joplin-rich-markdown#32]
2 small bugs: 
Links are formatted nicely when in a standard text block, but not when in a list. 
Mark syntax seems to be ignored. 

Text like this: 

![image](https://user-images.githubusercontent.com/4245227/149516393-7f1c81e4-eff4-4383-a602-97654efba956.png)

Rendered it looks like this: 

![image](https://user-images.githubusercontent.com/4245227/149516427-d245dba5-0980-4151-8a23-3d5df404ce64.png)

**Comment by CalebJohn** [comment]
> Links are formatted nicely when in a standard text block, but not when in a list.

This is not coming from the rich markdown plugin, this styling comes from the core app.

> Mark syntax seems to be ignored.

This is a mistake on my end, it seems you need to enable the "extra CSS" option to enable highlighting, but that was not my intention. I'll fix that in the next release.

**Comment by CalebJohn** [comment]
The mark issue will be fixed in the next release (v0.9.0)! Thanks for letting me know about it.
