### ISSUE TITLE
Keeps trying to load image when the url is invalid

### ISSUE THREAD

**Issue by laurent22** [CalebJohn/joplin-rich-markdown#33]
For example, if you create a note with this content:

```markdown
![invalid](https://joplinapp.org/invalid.png)
```

In that case it will keep trying to load "invalid.png" every 3 seconds, even if nothing else changes in the note.

**Comment by CalebJohn** [comment]
This is part of the system that scans for image changes (every 3 seconds by default). In hindsight it should have only been enabled for resources, and not all URLs. Luckily, the next version will [get rid of that](https://github.com/laurent22/joplin/commit/2660ff3af6232588de9092e3f8fdca68a06e8f5e), thanks to you :)
