### ISSUE TITLE
*Italics* and **Bold** Text Is Unchanged?

### ISSUE THREAD

**Issue by MrPoetry** [CalebJohn/joplin-rich-markdown#36]
Just installed Rich-Markdown, restarted Joplin, and in the MD editor *italicized* and **bold** words still look like all the other text (i.e. no added font-weight or slant). I'm using one other plugin, macos-native-theme. Am I missing something?

**Comment by CalebJohn** [comment]
> Am I missing something?

Just that italics and bold styling is not a feature of this plugin. That's actually a feature of the base application (below is a screenshot from a clean version of Joplin without any plugins).

![image](https://user-images.githubusercontent.com/2179547/150477813-cc837cae-49a8-4054-8aff-6c71286a41cd.png)

The macos-native-theme plugin overrides the Joplin css. You'll need to ask that plugin developer to add the styles you want back in, or you can [add the custom CSS](https://joplinapp.org/help/#custom-css) yourself. If you don't know how to do that, someone on the [forum](https://discourse.joplinapp.org/) will certainly be able to help you out if you ask.
