### ISSUE TITLE
[Feature Request] fold url in markdown editor

### ISSUE THREAD

**Issue by ylc395** [CalebJohn/joplin-rich-markdown#39]
`[link title](https://a-very-very-very-very-very-very-very-very-very-very-very-very-very-long-url.com)` will be folded as `[link title](...)`. And when hovering on `...`, url will be displayed in a tooltip.

If this is a acceptable feature, I can help to implement it.

**Comment by CalebJohn** [comment]
It's acceptable. I don't typically like hiding text in the source, but this will make notes with hyperlinks so much easier to read.

Let me know if you need any help implementing it. And please add an option to the settings that had this feature disabled by default.

**Comment by ylc395** [comment]
meet a problem: I need doing some cleanup when editor's current note has changed. Where can I put the cleanup code?

**Comment by CalebJohn** [comment]
For this feature you should add a new source file (maybe hideUrl.ts) inside that source file, you should export an `afterSourceChanges` function
example:
```
export function afterSourceChanges(cm: any) {
    <cleanup here>
}
```

This function will be called inside [richMarkdown.ts](https://github.com/CalebJohn/joplin-rich-markdown/blob/main/src/richMarkdown.ts#L110).

**Comment by ylc395** [comment]
@CalebJohn Sorry, I don't make it clear. I means that I want to do some clean up when the whole note has been replaced by other note.

**Comment by CalebJohn** [comment]
@ylc395 what's your purpose for that? You could use on_change in richMarkdown.ts if it's something lightweight. Or you can use [`joplin.workspace.onNoteSelectionChange`](https://joplinapp.org/api/references/plugin_api/classes/joplinworkspace.html#onnoteselectionchange) for something heavier.

**Comment by ylc395** [comment]
I'm implement this feature in https://discourse.joplinapp.org/t/plugin-note-link-system/21768/87 because it fits the topic of that plugin.

**Comment by CalebJohn** [comment]
Looks great! Thanks for cleaning this up!
