### ISSUE TITLE
Markdown rendering does not work entirely as it should

### ISSUE THREAD

**Issue by 0100110101001010** [CalebJohn/joplin-rich-markdown#43]
Jopling Desktop version: 2.8.8
Rich Markdown version: 0.9.0
OS: Ubuntu 22.04

## Problem

It does not look like how it should according to the screenshots in this repository's README (https://github.com/CalebJohn/joplin-rich-markdown#rich-markdown). The only thing that works is highlighting the currently selected line. Besides that I don't think there is any difference to the default markdown editor.

- I've tried both installation methods
- There are no other plugins installed
- Things like toggle checkboxes with Ctrl+Click are working

### Plugin settings
![Settings](https://user-images.githubusercontent.com/101060148/174446084-54f40062-1094-463f-9c66-197111c0d34f.png)

Unchecking **Add additional CSS classes for enhanced customization** does not change anything.

### Editor view
![Editor](https://user-images.githubusercontent.com/101060148/174446095-74ed286a-8af6-46e4-a797-6396f35d772b.png)

**Comment by CalebJohn** [comment]
This plugin doesn't provide enhanced styling for the using, but adds additional CSS classes that make it possible for users to add style themselves (with a few exceptions). 

I'll add a note that clarifies that in the readme.

**Comment by 0100110101001010** [comment]
Hey. Thanks for clarifying!

**Comment by CalebJohn** [comment]
To get the styling in that screenshot you can take a look at [this forum post](https://discourse.joplinapp.org/t/plugin-rich-markdown/15053/105). 

You just copy and paste the code from that post into a userchrome.css file. You can access that file through Settings (Settings -> Appearance -> Advanced -> Custom stylesheet for Joplin-wide app styles). Once you paste it in there (and save the file), you'll just need to update Joplin to get the styling. Fair warning though, having the hash tag (#) symbols shifted around can make the cursor movement a little less intuitive, but it shouldn't be too bad.
