### ISSUE TITLE
Issues with Links

### ISSUE THREAD

**Issue by moritz453** [CalebJohn/joplin-rich-markdown#47]
Hi,

I have an issue with Links. Whenever I have the app selected as my current app and I click on a link it opens the long form version. That is what I would expect. 

However, when I do then same thing while holding the “CMD” button I would expect the link would open. But it does not. It does the same thing as not holding the button.
To make this more confusing, when I click on a link, while holding the “CMD” button while having another app selected as my active one, the link opens without a problem.

Has anyone else had this issue? If yes, how can you fix it?

I would be grateful for any advice, as I use tons of links and it's a shame they are not working right.

Informatoin about the system:

- MacOS 13.0
- Apple Silicon M1Max
- Joplin 2.9.17
- Plugin – Latest Version

**Comment by CalebJohn** [comment]
Hi @moritz453 

I don't understand the issue that you're having. It sounds like you're saying that you're able to follow links when CMD is not pressed, but not when it is pressed? Is it possible that you have set that behavior in the settings?

**Comment by moritz453** [comment]
I have attached a little GIF (I hope that works on here) where I think you will be able to see the issue.
It seems that holding the CMD key sometimes works and sometimes not. In the GIF I never let go of the button. (The screens turns white as I was only recording part of the screen.) As you can see one time it works and one time it does not. I have found that being in the same row before clicking also increased my chances of it working. (Mind you I am always in markdown mode.)

Opening a link ALWAYS works when hold CMD and having another window active before clicking.

![Screenshot_2022-12-21_16 06 34](https://user-images.githubusercontent.com/71669090/208937616-114656b1-b867-4051-9bba-b7c4b0a70930.gif)

**Comment by moritz453** [comment]
One more thing I just realized. I think the issue may also be because by the following Plugin: https://github.com/SeptemberHX/joplin-plugin-enhancement

If that is the case, please accept my apologies for opening the issue in the wrong repo. I will move it immediately of course.

**Comment by CalebJohn** [comment]
Thanks for the gif, that really helps demonstrate the issue. Based on the gif I would guess that the issue that you're seeing does come from the enhancement plugin, because the hiding feature comes from there and not rich-markdown.

Do you have both plugins installed (enhancement and rich-markdown)? If so these plugins can actually conflict with each other causing issues like this. You should be able to uninstall this plugin without losing any behavior because the enhancement plugin actual includes the source code for this plugin, no need for both.
