### ISSUE TITLE
Broken titles/subtitles when used with Whitespace plugin

### ISSUE THREAD

**Issue by AZ2Tonez** [CalebJohn/joplin-rich-markdown#53]
Hello and thank you for this plugin! It's great not to have to use the split-view editor anymore! :)

I have noticed a small issue when the [Whitespace Plugin](https://github.com/marph91/joplin-plugin-whitespacer) is installed and enabled. That is, title/subtitle lines with the #'s out-dented don't render properly. Instead of starting at the left border/margin of the editing area, the text of the title/subtitle is also out-dented and so it renders on top of the #'s.

Whitespace plugin off:
![Joplin_2023-08-01_23-13-58](https://github.com/CalebJohn/joplin-rich-markdown/assets/2982767/97ccef1b-3308-435c-8ed1-08306b770641)

Whitespace plugin on:
![2023-08-01_23-12-49](https://github.com/CalebJohn/joplin-rich-markdown/assets/2982767/c15bf3dc-91f3-4386-bebf-b01fa04acaff)

(Apologies on the double-post - the other one used the incorrect account.)

**Comment by CalebJohn** [comment]
fixed in 3147042e14a46e7599301e885257bf6fc60c8df1

New release should be available in the next hour or so.

**Comment by AZ2Tonez** [comment]
Confirmed. Thank you!
