### ISSUE TITLE
[Feature] suppress *** when a line is rendered

### ISSUE THREAD

**Issue by MHoeller** [CalebJohn/joplin-rich-markdown#56]
Hi there,
thanks for the great plugin. 
Three asterix *** or --- render a horizontal line but the actual "letters" stay and underneath the line: 

![line](https://github.com/CalebJohn/joplin-rich-markdown/assets/11714953/476a6a25-938d-46a5-9427-e67472823eda)

I like to ask to suppress the letters as the # is in the headers. Alternatively this might be only a simple custom CSS which I could put to userchrome.css unfortunately I am do not know enough CSS to do this. If this is just a CSS hack I like to suggest to put a solution to tips.md

Thanks a lot,
Michael

**Comment by CalebJohn** [comment]
You can add `color: #00000000` to the horizontal rule css

```
/* Render horizontal lines (made with \-\-\- or \*\*\*) as an actual line across the editor. */
div.CodeMirror .cm-hr {
  border-top: 1px solid #777;
  display: block;
  line-height: 0px;
  color: #00000000;
}
```

**Comment by MHoeller** [comment]
Hi @CalebJohn 
this unfortunately does not the trick. I have put your css to userchrome.css but I get exactly the same results as shown above. I stopped joplin made the change and restartet joplin. Here are my settings: 
![image](https://github.com/CalebJohn/joplin-rich-markdown/assets/11714953/2f420b3c-2276-4dbd-9649-530be20b3547)
![image](https://github.com/CalebJohn/joplin-rich-markdown/assets/11714953/4701c751-d3a6-4af9-8aac-d3ce8fab378e)

**Comment by CalebJohn** [comment]
It likely just needs some tweaking. You should try asking for css help on the Joplin forum. The horizontal like stuff isn't part of this plugin, it's just css on top of Joplin, so there should be plenty of people familiar with it.
