### ISSUE TITLE
Please update the official Joplin Plugin Repository

### ISSUE THREAD

**Issue by pomberger** [CalebJohn/joplin-rich-markdown#6]
I recongnized that the plugin in the official Joplin Plugin Repository is not up to date, but shows the same version number.

(I installed the plugin fom the "Plugins" section in the Configuration screen and the customization for highlighting the active line did not work.  Installing the plugin form the file in this repository solved the problem)

**Comment by CalebJohn** [comment]
The plugin repository has the most recent release of this plugin (0.3.2). I'm working on preparing the next release and will update the version number accordingly when it's ready. I hope to have v0.4.0 ready sometime in the next week.
