### ISSUE TITLE
[Feature Request] Improve Syntax Highlighting of Code Blocks

### ISSUE THREAD

**Issue by fgebhart** [CalebJohn/joplin-rich-markdown#60]
Hi :wave: great plugin! Thanks for creating and maintaining!

I was wondering whether it would be possible to enhance the syntax highlighting of code blocks in the rich markdown editor. I found the syntax highlighting to be rather weak compared to other syntax highlighting editors out there.

Here is an example of Joplin using Joplin (2.14.20) and joplin-rich-markdown (0.13.3 - though not sure where to check the installed version, tbh) versions:
![joplin](https://github.com/CalebJohn/joplin-rich-markdown/assets/16943048/0b88ca5e-7890-4379-94a7-b57d20bb66f5)

And here an example of e.g. VSCode:
![vscode](https://github.com/CalebJohn/joplin-rich-markdown/assets/16943048/8a060be2-a218-4945-a8a3-5be281b17d03)

As you can see in VSCode many more tokens are highlighted.

Note, that I did came across joplin-plugin-enhancement, which seems to have an improved highlighting (besides many more features), but at least for me it breaks the monospacing of the code block, see:
![enhancement](https://github.com/CalebJohn/joplin-rich-markdown/assets/16943048/47ba2ee2-75d6-4aee-8e51-a99dc309e6f0)

Also, I believe improving the highlighting of code blocks in joplin-rich-markdown has value in itself.

Happy to discuss. 

Edit: Have updated my Joplin to 2.14.20, but still the same behavior.

**Comment by CalebJohn** [comment]
Syntax highlighting is handled by the base application not rich-markdown. I think it would make sense to extend this plugin to have more beautiful syntax highlighting, but it's probably not necessary. Joplin is currently in the process of swapping the main text editing component (cm5) for a newer version (cm6). The syntax highlighting will change in that process. For example, I tried your example in the beta editor.

![image](https://github.com/CalebJohn/joplin-rich-markdown/assets/2179547/5e73dfe5-911a-45e0-9352-821a5fee790d)

I'm not sure which languages are supported, but your above examples should be. You can try out this editor for yourself by toggling on the beta editor under (Options -> General -> Opt-in to the editor beta).

I'm going to close this issue for now, but feel free to re-open if you have some specific requests that aren't fulfilled in the new editor.
