### ISSUE TITLE
Issue : "==text==" is not anymore highlighted since Joplin 3.1.20 (Mac OS)

### ISSUE THREAD

**Issue by nokoa77** [CalebJohn/joplin-rich-markdown#68]
Hi,
Since Joplin 3.1.20, "==text==" is not anymore highlighted in my notes.
I'm on mac OS.
I use this userchrome.css : 
```
/* For styling the entire Joplin app (except the rendered Markdown, which is defined in `userstyle.css`) */

/* Render horizontal lines (made with \-\-\- or \*\*\*) as an actual line across the editor. */
.cm-hr {
  border-top: 1px solid #777;
  display: block;
  line-height: 0px;
}

/* strikeout and dim the text of a checked checkbox */
span.cm-rm-checkbox.cm-property + span.cm-rm-checkbox ~ span.cm-rm-checkbox {
	text-decoration: line-through;
	opacity: 0.7;
}


/* .cm-header-1 {
/*  display: inline-block;
/*   margin-top:.8em;
/*   margin-bottom:.3em;
/*   }
```

**Comment by gcharFR** [comment]
Same for me on Linux, with no specific css.

exemple : 
![image](https://github.com/user-attachments/assets/a90302be-5446-485a-9763-b59181604ba0)

It works back when switching from the new markdown editor (which Joplin 3.1.20 uses by default) to the legacy one.

version of Rich Markdown plugin used : 0.15.0 (latest to date)

**Comment by CalebJohn** [comment]
This was caused by a bit of missing styling that is necessary for the new editor to work. I've pushed an update and will be releasing a new version right away

**Comment by gcharFR** [comment]
Thanks a lot !Le 2 nov. 2024 à 21:27, Caleb John ***@***.***> a écrit :﻿
This was caused by a bit of missing styling that is necessary for the new editor to work. I've pushed an update and will be releasing a new version right away
