### ISSUE TITLE
[Feature Request] Add support for expand/collapse text option in menu bar

### ISSUE THREAD

**Issue by mvangriet** [CalebJohn/joplin-rich-markdown#72]
Hi, I am a big fan of using the expand/collapse option in my text, to make it more easy to read. Can you add the option in the menu bar to add this section more easily? BrMarkus

<details open>
  <summary>Hello</summary>
  World!
</details>

**Comment by CalebJohn** [comment]
Hi,

The purpose of this plugin is to improve rendering of notes in the editor. So this request does not fit in with the features of this plugin.

Maybe you will find the [template plugin](https://joplinapp.org/plugins/plugin/joplin.plugin.templates/?from-tab=home) useful.
