### ISSUE TITLE
[Feature request] Add text coloring and styles to WYSIWYG

### ISSUE THREAD

**Issue by omega3** [CalebJohn/joplin-rich-markdown#9]
Reference:
https://stackoverflow.com/questions/35465557/how-to-apply-color-in-markdown

https://bookdown.org/yihui/rmarkdown-cookbook/font-color.html

https://www.programmersought.com/article/77384514692/

I want to use Joplin to create my own English grammar notebook and having more options to distinguish text is essential for me. Only basic options such as here on forum, or such as Joplin has would dramatically limit the ability to use Joplin for my purpose.

By writing this I want to emphasize that very basic features can determine whether a program can fulfill a certain purpose or not. Please, take it into consideration.

Cross-out feature, more text coloring and text background color options, upper index, strike-through, underline, etc. Whatever you add, someone will find it useful.

Actually, it would be nice to have such icons to color font as they are in for example LibreOffice Writer and with the same functionality. I believe it is a standard way of handling coloring text in many applications.

Also it would be nice to have plugins to create predefined, custom styles of formatting text, similar to text styles in MS Word and to create predefined, custom text separators, for example:
`-------------------------`
or
`***`
or whatever can be predefined. I imagine I could add an icon to editor with predefined style or separator.

I am perfectly aware that Joplin is not a text editor, like MS Word or LO Writer but anyway, options to distinguish text can greatly enhance usability of the program.

**Comment by CalebJohn** [comment]
Hi @omega3, I'm having a bit of trouble understanding exactly what you're requesting. I can't see anything in your post that isn't already supported in Joplin, aside from maybe having some convenient toolbar buttons, but that's not in the scope of this plugin.

Could you write a list with your direct requests?

**Comment by CalebJohn** [comment]
Hi @omega3  The purpose of this plugin is specifically to cater to markdown users like myself. For me, this means relying less on buttons and relying on characters in the editor, for example, a strikethrough is written like so `~~I'm stricken!~~` and will render as ~~\~\~I'm stricken!\~\~~~ in the markdown editor. This is the purpose of the plugin. This plugin caters specifically to users who **do not** want to use the WYSIWYG interface. I can understand your use case, and I agree that it is vital. It's just that this plugin is meant to do something different, and cater to a different type of user.

> At least can you provide some instructions how to add buttons to make "life a little bit nicer."

What you are looking for is not the Rich Markdown plugin, you want the [Menu Shortcut Toolbar plugin](https://discourse.joplinapp.org/t/menu-items-shortcuts-toolbar-icons/17372). You can install it from within Joplin Tools -> Options -> Plugins and searching for "menu items". This plugin adds toolbar buttons and shortcuts for mark, strikethrough, underline, superscript, and subscript.


> I have no idea how to enable it.

Tools -> Options -> Rich Markdown -> Add additional CSS classes for enhanced customization. But this does not add a button, it just adds additional CSS styling for power users. I don't think it will be useful for you.

I hope this was helpful for you.
